version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 127.0.0.1:2181:2181
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - 127.0.0.1::9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      # KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      # KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
